name: Run Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.300
      - name: Run Tests
        run: dotnet test     
