name: Run Tests

on: push

jobs:
  dotnet:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: dotnet test